services:
  db:
    image: postgres
    restart: always
    shm_size: 512mb
    env_file:
      - ./server/.env
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - './server/docker/dev:/docker-entrypoint-initdb.d'
    networks:
      - dialog_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile-prod
      args:
        - PORT
    env_file:
      - ./server/.env
    container_name: server_api
    restart: always
    ports:
      - 5555:5555
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - dialog_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_app
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./client/.env
    depends_on:
      - server
    networks:
      - dialog_network

volumes:
  db_data:

networks:
  dialog_network:
    driver: bridge